//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBTheCoffeeEntities : DbContext
    {
        public DBTheCoffeeEntities()
            : base("name=DBTheCoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<View_BaoCaoDoanhThu> View_BaoCaoDoanhThu { get; set; }
        public virtual DbSet<View_DanhSachHangDaDat> View_DanhSachHangDaDat { get; set; }
        public virtual DbSet<View_ThongKeSanPhamTheoDanhMuc> View_ThongKeSanPhamTheoDanhMuc { get; set; }
    
        public virtual ObjectResult<string> sp_ChangePassword(string username, string password_old, string password_new, string confirmPass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var password_oldParameter = password_old != null ?
                new ObjectParameter("password_old", password_old) :
                new ObjectParameter("password_old", typeof(string));
    
            var password_newParameter = password_new != null ?
                new ObjectParameter("password_new", password_new) :
                new ObjectParameter("password_new", typeof(string));
    
            var confirmPassParameter = confirmPass != null ?
                new ObjectParameter("confirmPass", confirmPass) :
                new ObjectParameter("confirmPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ChangePassword", usernameParameter, password_oldParameter, password_newParameter, confirmPassParameter);
        }
    
        public virtual ObjectResult<sp_CheckLogin_Result> sp_CheckLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CheckLogin_Result>("sp_CheckLogin", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_DeleteOrder(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteOrder", idParameter);
        }
    
        public virtual int sp_DeleteProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteProduct", idParameter);
        }
    
        public virtual int sp_DeleteTransaction(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteTransaction", idParameter);
        }
    
        public virtual int sp_DeleteUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUser", usernameParameter);
        }
    
        public virtual ObjectResult<sp_getAllProduct_Result> sp_getAllProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllProduct_Result>("sp_getAllProduct");
        }
    
        public virtual ObjectResult<sp_getOrderDetail_Result> sp_getOrderDetail(string username, Nullable<int> transactionID)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var transactionIDParameter = transactionID.HasValue ?
                new ObjectParameter("transactionID", transactionID) :
                new ObjectParameter("transactionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOrderDetail_Result>("sp_getOrderDetail", usernameParameter, transactionIDParameter);
        }
    
        public virtual ObjectResult<sp_getProduct_Result> sp_getProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getProduct_Result>("sp_getProduct", idParameter);
        }
    
        public virtual ObjectResult<sp_getTransactionByUser_Result> sp_getTransactionByUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getTransactionByUser_Result>("sp_getTransactionByUser", usernameParameter);
        }
    
        public virtual ObjectResult<sp_getTransactionByUserForDate_Result> sp_getTransactionByUserForDate(string username, string datefrom, string dateto)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var datefromParameter = datefrom != null ?
                new ObjectParameter("datefrom", datefrom) :
                new ObjectParameter("datefrom", typeof(string));
    
            var datetoParameter = dateto != null ?
                new ObjectParameter("dateto", dateto) :
                new ObjectParameter("dateto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getTransactionByUserForDate_Result>("sp_getTransactionByUserForDate", usernameParameter, datefromParameter, datetoParameter);
        }
    
        public virtual ObjectResult<sp_InfoUser_Result> sp_InfoUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InfoUser_Result>("sp_InfoUser", usernameParameter);
        }
    
        public virtual int sp_InsertOrder(string username, Nullable<int> transactionID, Nullable<int> productID, Nullable<int> quantity)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var transactionIDParameter = transactionID.HasValue ?
                new ObjectParameter("transactionID", transactionID) :
                new ObjectParameter("transactionID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertOrder", usernameParameter, transactionIDParameter, productIDParameter, quantityParameter);
        }
    
        public virtual int sp_InsertProduct(Nullable<int> categoriesID, Nullable<int> supplierID, string pro_name, Nullable<int> pro_quantity, Nullable<double> pro_firstprice, Nullable<double> pro_price, Nullable<System.DateTime> pro_nsx, Nullable<System.DateTime> pro_hsd, string pro_description)
        {
            var categoriesIDParameter = categoriesID.HasValue ?
                new ObjectParameter("categoriesID", categoriesID) :
                new ObjectParameter("categoriesID", typeof(int));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("supplierID", supplierID) :
                new ObjectParameter("supplierID", typeof(int));
    
            var pro_nameParameter = pro_name != null ?
                new ObjectParameter("pro_name", pro_name) :
                new ObjectParameter("pro_name", typeof(string));
    
            var pro_quantityParameter = pro_quantity.HasValue ?
                new ObjectParameter("pro_quantity", pro_quantity) :
                new ObjectParameter("pro_quantity", typeof(int));
    
            var pro_firstpriceParameter = pro_firstprice.HasValue ?
                new ObjectParameter("pro_firstprice", pro_firstprice) :
                new ObjectParameter("pro_firstprice", typeof(double));
    
            var pro_priceParameter = pro_price.HasValue ?
                new ObjectParameter("pro_price", pro_price) :
                new ObjectParameter("pro_price", typeof(double));
    
            var pro_nsxParameter = pro_nsx.HasValue ?
                new ObjectParameter("pro_nsx", pro_nsx) :
                new ObjectParameter("pro_nsx", typeof(System.DateTime));
    
            var pro_hsdParameter = pro_hsd.HasValue ?
                new ObjectParameter("pro_hsd", pro_hsd) :
                new ObjectParameter("pro_hsd", typeof(System.DateTime));
    
            var pro_descriptionParameter = pro_description != null ?
                new ObjectParameter("pro_description", pro_description) :
                new ObjectParameter("pro_description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertProduct", categoriesIDParameter, supplierIDParameter, pro_nameParameter, pro_quantityParameter, pro_firstpriceParameter, pro_priceParameter, pro_nsxParameter, pro_hsdParameter, pro_descriptionParameter);
        }
    
        public virtual int sp_InsertTransaction(string username, string address, string phone, Nullable<System.DateTime> createdate, string note)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("createdate", createdate) :
                new ObjectParameter("createdate", typeof(System.DateTime));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertTransaction", usernameParameter, addressParameter, phoneParameter, createdateParameter, noteParameter);
        }
    
        public virtual int sp_InsertUser(string username, string password, string firstname, string lastname, string address, Nullable<System.DateTime> birthday, string gender, string phone, string email, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("birthday", birthday) :
                new ObjectParameter("birthday", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertUser", usernameParameter, passwordParameter, firstnameParameter, lastnameParameter, addressParameter, birthdayParameter, genderParameter, phoneParameter, emailParameter, roleParameter);
        }
    
        public virtual int sp_Permission(string username, string password, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Permission", usernameParameter, passwordParameter, roleParameter);
        }
    
        public virtual int sp_Register(string username, string password, string confirmpassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var confirmpasswordParameter = confirmpassword != null ?
                new ObjectParameter("confirmpassword", confirmpassword) :
                new ObjectParameter("confirmpassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Register", usernameParameter, passwordParameter, confirmpasswordParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemSanPhamTheoTen_Result> sp_TimKiemSanPhamTheoTen(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemSanPhamTheoTen_Result>("sp_TimKiemSanPhamTheoTen", nameParameter);
        }
    
        public virtual int sp_UpdateOrder(Nullable<int> id, Nullable<int> quantity)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateOrder", idParameter, quantityParameter);
        }
    
        public virtual int sp_UpdateProduct(Nullable<int> id, Nullable<int> categoriesID, Nullable<int> supplierID, string name, Nullable<int> quantity, Nullable<float> firstprice, Nullable<float> price, Nullable<System.DateTime> nsx, Nullable<System.DateTime> hsd, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var categoriesIDParameter = categoriesID.HasValue ?
                new ObjectParameter("categoriesID", categoriesID) :
                new ObjectParameter("categoriesID", typeof(int));
    
            var supplierIDParameter = supplierID.HasValue ?
                new ObjectParameter("supplierID", supplierID) :
                new ObjectParameter("supplierID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var firstpriceParameter = firstprice.HasValue ?
                new ObjectParameter("firstprice", firstprice) :
                new ObjectParameter("firstprice", typeof(float));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(float));
    
            var nsxParameter = nsx.HasValue ?
                new ObjectParameter("nsx", nsx) :
                new ObjectParameter("nsx", typeof(System.DateTime));
    
            var hsdParameter = hsd.HasValue ?
                new ObjectParameter("hsd", hsd) :
                new ObjectParameter("hsd", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateProduct", idParameter, categoriesIDParameter, supplierIDParameter, nameParameter, quantityParameter, firstpriceParameter, priceParameter, nsxParameter, hsdParameter, descriptionParameter);
        }
    
        public virtual int sp_UpdateUser(string username, string password, string firstname, string lastname, string address, Nullable<System.DateTime> birthday, string gender, string phone, string email, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("birthday", birthday) :
                new ObjectParameter("birthday", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateUser", usernameParameter, passwordParameter, firstnameParameter, lastnameParameter, addressParameter, birthdayParameter, genderParameter, phoneParameter, emailParameter, roleParameter);
        }
    }
}
