//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class User
    {
        public List<Order> listOrder;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string us_username { get; set; }
        public string us_password { get; set; }
        public string us_firstname { get; set; }
        public string us_lastname { get; set; }
        public string us_address { get; set; }
        public System.DateTime us_birthday { get; set; }
        public string us_gender { get; set; }
        public string us_phone { get; set; }
        public string us_email { get; set; }
        public string us_role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public DataTable orderTable { get; set; }
    }
}
