//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BaoCaoDoanhThu
    {
        public int id { get; set; }
        public string us_username { get; set; }
        public float totalprice { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
