//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ThongKeSanPhamTheoDanhMuc
    {
        public string cate_name { get; set; }
        public string sup_name { get; set; }
        public string pro_name { get; set; }
        public int pro_quantity { get; set; }
        public float pro_firstprice { get; set; }
        public float pro_price { get; set; }
        public System.DateTime pro_nsx { get; set; }
        public System.DateTime pro_hsd { get; set; }
        public string pro_description { get; set; }
    }
}
