//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DanhSachHangDaDat
    {
        public string us_username { get; set; }
        public int transactionID { get; set; }
        public int orderID { get; set; }
        public string pro_name { get; set; }
        public int or_quantity { get; set; }
        public Nullable<float> or_price { get; set; }
    }
}
