#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffee
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DIEPFAMILY")]
	public partial class TheCoffeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertOrder(Order instance);
    partial void UpdateOrder(Order instance);
    partial void DeleteOrder(Order instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertSupplier(Supplier instance);
    partial void UpdateSupplier(Supplier instance);
    partial void DeleteSupplier(Supplier instance);
    partial void InsertTransaction(Transaction instance);
    partial void UpdateTransaction(Transaction instance);
    partial void DeleteTransaction(Transaction instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public TheCoffeDataContext() : 
				base(global::TheCoffee.Properties.Settings.Default.DIEPFAMILYConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TheCoffeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TheCoffeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TheCoffeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TheCoffeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<Order> Orders
		{
			get
			{
				return this.GetTable<Order>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Supplier> Suppliers
		{
			get
			{
				return this.GetTable<Supplier>();
			}
		}
		
		public System.Data.Linq.Table<Transaction> Transactions
		{
			get
			{
				return this.GetTable<Transaction>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<View_BaoCaoDoanhThu> View_BaoCaoDoanhThus
		{
			get
			{
				return this.GetTable<View_BaoCaoDoanhThu>();
			}
		}
		
		public System.Data.Linq.Table<View_DanhSachHangDaDat> View_DanhSachHangDaDats
		{
			get
			{
				return this.GetTable<View_DanhSachHangDaDat>();
			}
		}
		
		public System.Data.Linq.Table<View_ThongKeSanPhamTheoDanhMuc> View_ThongKeSanPhamTheoDanhMucs
		{
			get
			{
				return this.GetTable<View_ThongKeSanPhamTheoDanhMuc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _cate_totalproduct;
		
		private string _cate_name;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncate_totalproductChanging(System.Nullable<int> value);
    partial void Oncate_totalproductChanged();
    partial void Oncate_nameChanging(string value);
    partial void Oncate_nameChanged();
    #endregion
		
		public Category()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_totalproduct", DbType="Int")]
		public System.Nullable<int> cate_totalproduct
		{
			get
			{
				return this._cate_totalproduct;
			}
			set
			{
				if ((this._cate_totalproduct != value))
				{
					this.Oncate_totalproductChanging(value);
					this.SendPropertyChanging();
					this._cate_totalproduct = value;
					this.SendPropertyChanged("cate_totalproduct");
					this.Oncate_totalproductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cate_name
		{
			get
			{
				return this._cate_name;
			}
			set
			{
				if ((this._cate_name != value))
				{
					this.Oncate_nameChanging(value);
					this.SendPropertyChanging();
					this._cate_name = value;
					this.SendPropertyChanged("cate_name");
					this.Oncate_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product", Storage="_Products", ThisKey="id", OtherKey="categoriesID")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Order]")]
	public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _us_username;
		
		private int _transactionID;
		
		private int _productID;
		
		private int _or_quantity;
		
		private System.Nullable<float> _or_price;
		
		private EntityRef<Product> _Product;
		
		private EntityRef<Transaction> _Transaction;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onus_usernameChanging(string value);
    partial void Onus_usernameChanged();
    partial void OntransactionIDChanging(int value);
    partial void OntransactionIDChanged();
    partial void OnproductIDChanging(int value);
    partial void OnproductIDChanged();
    partial void Onor_quantityChanging(int value);
    partial void Onor_quantityChanged();
    partial void Onor_priceChanging(System.Nullable<float> value);
    partial void Onor_priceChanged();
    #endregion
		
		public Order()
		{
			this._Product = default(EntityRef<Product>);
			this._Transaction = default(EntityRef<Transaction>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_username", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string us_username
		{
			get
			{
				return this._us_username;
			}
			set
			{
				if ((this._us_username != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onus_usernameChanging(value);
					this.SendPropertyChanging();
					this._us_username = value;
					this.SendPropertyChanged("us_username");
					this.Onus_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transactionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int transactionID
		{
			get
			{
				return this._transactionID;
			}
			set
			{
				if ((this._transactionID != value))
				{
					if (this._Transaction.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntransactionIDChanging(value);
					this.SendPropertyChanging();
					this._transactionID = value;
					this.SendPropertyChanged("transactionID");
					this.OntransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_quantity", DbType="Int NOT NULL")]
		public int or_quantity
		{
			get
			{
				return this._or_quantity;
			}
			set
			{
				if ((this._or_quantity != value))
				{
					this.Onor_quantityChanging(value);
					this.SendPropertyChanging();
					this._or_quantity = value;
					this.SendPropertyChanged("or_quantity");
					this.Onor_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_price", DbType="Real")]
		public System.Nullable<float> or_price
		{
			get
			{
				return this._or_price;
			}
			set
			{
				if ((this._or_price != value))
				{
					this.Onor_priceChanging(value);
					this.SendPropertyChanging();
					this._or_price = value;
					this.SendPropertyChanged("or_price");
					this.Onor_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Order", Storage="_Product", ThisKey="productID", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.Orders.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.Orders.Add(this);
						this._productID = value.id;
					}
					else
					{
						this._productID = default(int);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaction_Order", Storage="_Transaction", ThisKey="transactionID", OtherKey="id", IsForeignKey=true)]
		public Transaction Transaction
		{
			get
			{
				return this._Transaction.Entity;
			}
			set
			{
				Transaction previousValue = this._Transaction.Entity;
				if (((previousValue != value) 
							|| (this._Transaction.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaction.Entity = null;
						previousValue.Orders.Remove(this);
					}
					this._Transaction.Entity = value;
					if ((value != null))
					{
						value.Orders.Add(this);
						this._transactionID = value.id;
					}
					else
					{
						this._transactionID = default(int);
					}
					this.SendPropertyChanged("Transaction");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Order", Storage="_User", ThisKey="us_username", OtherKey="us_username", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Orders.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Orders.Add(this);
						this._us_username = value.us_username;
					}
					else
					{
						this._us_username = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _categoriesID;
		
		private int _supplierID;
		
		private string _pro_name;
		
		private int _pro_quantity;
		
		private System.Nullable<double> _pro_firstprice;
		
		private System.Nullable<double> _pro_price;
		
		private string _pro_description;
		
		private System.DateTime _pro_nsx;
		
		private System.DateTime _pro_hsd;
		
		private EntitySet<Order> _Orders;
		
		private EntityRef<Category> _Category;
		
		private EntityRef<Supplier> _Supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncategoriesIDChanging(int value);
    partial void OncategoriesIDChanged();
    partial void OnsupplierIDChanging(int value);
    partial void OnsupplierIDChanged();
    partial void Onpro_nameChanging(string value);
    partial void Onpro_nameChanged();
    partial void Onpro_quantityChanging(int value);
    partial void Onpro_quantityChanged();
    partial void Onpro_firstpriceChanging(System.Nullable<double> value);
    partial void Onpro_firstpriceChanged();
    partial void Onpro_priceChanging(System.Nullable<double> value);
    partial void Onpro_priceChanged();
    partial void Onpro_descriptionChanging(string value);
    partial void Onpro_descriptionChanged();
    partial void Onpro_nsxChanging(System.DateTime value);
    partial void Onpro_nsxChanged();
    partial void Onpro_hsdChanging(System.DateTime value);
    partial void Onpro_hsdChanged();
    #endregion
		
		public Product()
		{
			this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
			this._Category = default(EntityRef<Category>);
			this._Supplier = default(EntityRef<Supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoriesID", DbType="Int NOT NULL")]
		public int categoriesID
		{
			get
			{
				return this._categoriesID;
			}
			set
			{
				if ((this._categoriesID != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategoriesIDChanging(value);
					this.SendPropertyChanging();
					this._categoriesID = value;
					this.SendPropertyChanged("categoriesID");
					this.OncategoriesIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplierID", DbType="Int NOT NULL")]
		public int supplierID
		{
			get
			{
				return this._supplierID;
			}
			set
			{
				if ((this._supplierID != value))
				{
					if (this._Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsupplierIDChanging(value);
					this.SendPropertyChanging();
					this._supplierID = value;
					this.SendPropertyChanged("supplierID");
					this.OnsupplierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_name
		{
			get
			{
				return this._pro_name;
			}
			set
			{
				if ((this._pro_name != value))
				{
					this.Onpro_nameChanging(value);
					this.SendPropertyChanging();
					this._pro_name = value;
					this.SendPropertyChanged("pro_name");
					this.Onpro_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_quantity", DbType="Int NOT NULL")]
		public int pro_quantity
		{
			get
			{
				return this._pro_quantity;
			}
			set
			{
				if ((this._pro_quantity != value))
				{
					this.Onpro_quantityChanging(value);
					this.SendPropertyChanging();
					this._pro_quantity = value;
					this.SendPropertyChanged("pro_quantity");
					this.Onpro_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_firstprice", DbType="Float")]
		public System.Nullable<double> pro_firstprice
		{
			get
			{
				return this._pro_firstprice;
			}
			set
			{
				if ((this._pro_firstprice != value))
				{
					this.Onpro_firstpriceChanging(value);
					this.SendPropertyChanging();
					this._pro_firstprice = value;
					this.SendPropertyChanged("pro_firstprice");
					this.Onpro_firstpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="Float")]
		public System.Nullable<double> pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this.Onpro_priceChanging(value);
					this.SendPropertyChanging();
					this._pro_price = value;
					this.SendPropertyChanged("pro_price");
					this.Onpro_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_description", DbType="NVarChar(100)")]
		public string pro_description
		{
			get
			{
				return this._pro_description;
			}
			set
			{
				if ((this._pro_description != value))
				{
					this.Onpro_descriptionChanging(value);
					this.SendPropertyChanging();
					this._pro_description = value;
					this.SendPropertyChanged("pro_description");
					this.Onpro_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nsx", DbType="Date NOT NULL")]
		public System.DateTime pro_nsx
		{
			get
			{
				return this._pro_nsx;
			}
			set
			{
				if ((this._pro_nsx != value))
				{
					this.Onpro_nsxChanging(value);
					this.SendPropertyChanging();
					this._pro_nsx = value;
					this.SendPropertyChanged("pro_nsx");
					this.Onpro_nsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_hsd", DbType="Date NOT NULL")]
		public System.DateTime pro_hsd
		{
			get
			{
				return this._pro_hsd;
			}
			set
			{
				if ((this._pro_hsd != value))
				{
					this.Onpro_hsdChanging(value);
					this.SendPropertyChanging();
					this._pro_hsd = value;
					this.SendPropertyChanged("pro_hsd");
					this.Onpro_hsdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_Order", Storage="_Orders", ThisKey="id", OtherKey="productID")]
		public EntitySet<Order> Orders
		{
			get
			{
				return this._Orders;
			}
			set
			{
				this._Orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Product", Storage="_Category", ThisKey="categoriesID", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._categoriesID = value.id;
					}
					else
					{
						this._categoriesID = default(int);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Product", Storage="_Supplier", ThisKey="supplierID", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Supplier Supplier
		{
			get
			{
				return this._Supplier.Entity;
			}
			set
			{
				Supplier previousValue = this._Supplier.Entity;
				if (((previousValue != value) 
							|| (this._Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Supplier.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Supplier.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._supplierID = value.id;
					}
					else
					{
						this._supplierID = default(int);
					}
					this.SendPropertyChanged("Supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Supplier")]
	public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sup_name;
		
		private string _sup_phone;
		
		private string _sup_address;
		
		private EntitySet<Product> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsup_nameChanging(string value);
    partial void Onsup_nameChanged();
    partial void Onsup_phoneChanging(string value);
    partial void Onsup_phoneChanged();
    partial void Onsup_addressChanging(string value);
    partial void Onsup_addressChanged();
    #endregion
		
		public Supplier()
		{
			this._Products = new EntitySet<Product>(new Action<Product>(this.attach_Products), new Action<Product>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sup_name
		{
			get
			{
				return this._sup_name;
			}
			set
			{
				if ((this._sup_name != value))
				{
					this.Onsup_nameChanging(value);
					this.SendPropertyChanging();
					this._sup_name = value;
					this.SendPropertyChanged("sup_name");
					this.Onsup_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_phone", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string sup_phone
		{
			get
			{
				return this._sup_phone;
			}
			set
			{
				if ((this._sup_phone != value))
				{
					this.Onsup_phoneChanging(value);
					this.SendPropertyChanging();
					this._sup_phone = value;
					this.SendPropertyChanged("sup_phone");
					this.Onsup_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sup_address
		{
			get
			{
				return this._sup_address;
			}
			set
			{
				if ((this._sup_address != value))
				{
					this.Onsup_addressChanging(value);
					this.SendPropertyChanging();
					this._sup_address = value;
					this.SendPropertyChanged("sup_address");
					this.Onsup_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Supplier_Product", Storage="_Products", ThisKey="id", OtherKey="supplierID")]
		public EntitySet<Product> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = this;
		}
		
		private void detach_Products(Product entity)
		{
			this.SendPropertyChanging();
			entity.Supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Transaction]")]
	public partial class Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _us_username;
		
		private string _addressTo;
		
		private string _phoneTo;
		
		private float _totalprice;
		
		private System.DateTime _createdate;
		
		private string _note;
		
		private EntitySet<Order> _Orders;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onus_usernameChanging(string value);
    partial void Onus_usernameChanged();
    partial void OnaddressToChanging(string value);
    partial void OnaddressToChanged();
    partial void OnphoneToChanging(string value);
    partial void OnphoneToChanged();
    partial void OntotalpriceChanging(float value);
    partial void OntotalpriceChanged();
    partial void OncreatedateChanging(System.DateTime value);
    partial void OncreatedateChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
		
		public Transaction()
		{
			this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string us_username
		{
			get
			{
				return this._us_username;
			}
			set
			{
				if ((this._us_username != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onus_usernameChanging(value);
					this.SendPropertyChanging();
					this._us_username = value;
					this.SendPropertyChanged("us_username");
					this.Onus_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressTo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string addressTo
		{
			get
			{
				return this._addressTo;
			}
			set
			{
				if ((this._addressTo != value))
				{
					this.OnaddressToChanging(value);
					this.SendPropertyChanging();
					this._addressTo = value;
					this.SendPropertyChanged("addressTo");
					this.OnaddressToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneTo", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string phoneTo
		{
			get
			{
				return this._phoneTo;
			}
			set
			{
				if ((this._phoneTo != value))
				{
					this.OnphoneToChanging(value);
					this.SendPropertyChanging();
					this._phoneTo = value;
					this.SendPropertyChanged("phoneTo");
					this.OnphoneToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalprice", DbType="Real NOT NULL")]
		public float totalprice
		{
			get
			{
				return this._totalprice;
			}
			set
			{
				if ((this._totalprice != value))
				{
					this.OntotalpriceChanging(value);
					this.SendPropertyChanging();
					this._totalprice = value;
					this.SendPropertyChanged("totalprice");
					this.OntotalpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="Date NOT NULL")]
		public System.DateTime createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this.OncreatedateChanging(value);
					this.SendPropertyChanging();
					this._createdate = value;
					this.SendPropertyChanged("createdate");
					this.OncreatedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(100)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaction_Order", Storage="_Orders", ThisKey="id", OtherKey="transactionID")]
		public EntitySet<Order> Orders
		{
			get
			{
				return this._Orders;
			}
			set
			{
				this._Orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Transaction", Storage="_User", ThisKey="us_username", OtherKey="us_username", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Transactions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Transactions.Add(this);
						this._us_username = value.us_username;
					}
					else
					{
						this._us_username = default(string);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.Transaction = this;
		}
		
		private void detach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.Transaction = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _us_username;
		
		private string _us_password;
		
		private string _us_firstname;
		
		private string _us_lastname;
		
		private string _us_address;
		
		private System.DateTime _us_birthday;
		
		private char _us_gender;
		
		private string _us_phone;
		
		private string _us_email;
		
		private string _us_role;
		
		private EntitySet<Order> _Orders;
		
		private EntitySet<Transaction> _Transactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onus_usernameChanging(string value);
    partial void Onus_usernameChanged();
    partial void Onus_passwordChanging(string value);
    partial void Onus_passwordChanged();
    partial void Onus_firstnameChanging(string value);
    partial void Onus_firstnameChanged();
    partial void Onus_lastnameChanging(string value);
    partial void Onus_lastnameChanged();
    partial void Onus_addressChanging(string value);
    partial void Onus_addressChanged();
    partial void Onus_birthdayChanging(System.DateTime value);
    partial void Onus_birthdayChanged();
    partial void Onus_genderChanging(char value);
    partial void Onus_genderChanged();
    partial void Onus_phoneChanging(string value);
    partial void Onus_phoneChanged();
    partial void Onus_emailChanging(string value);
    partial void Onus_emailChanged();
    partial void Onus_roleChanging(string value);
    partial void Onus_roleChanged();
    #endregion
		
		public User()
		{
			this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
			this._Transactions = new EntitySet<Transaction>(new Action<Transaction>(this.attach_Transactions), new Action<Transaction>(this.detach_Transactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_username", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string us_username
		{
			get
			{
				return this._us_username;
			}
			set
			{
				if ((this._us_username != value))
				{
					this.Onus_usernameChanging(value);
					this.SendPropertyChanging();
					this._us_username = value;
					this.SendPropertyChanged("us_username");
					this.Onus_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string us_password
		{
			get
			{
				return this._us_password;
			}
			set
			{
				if ((this._us_password != value))
				{
					this.Onus_passwordChanging(value);
					this.SendPropertyChanging();
					this._us_password = value;
					this.SendPropertyChanged("us_password");
					this.Onus_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string us_firstname
		{
			get
			{
				return this._us_firstname;
			}
			set
			{
				if ((this._us_firstname != value))
				{
					this.Onus_firstnameChanging(value);
					this.SendPropertyChanging();
					this._us_firstname = value;
					this.SendPropertyChanged("us_firstname");
					this.Onus_firstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string us_lastname
		{
			get
			{
				return this._us_lastname;
			}
			set
			{
				if ((this._us_lastname != value))
				{
					this.Onus_lastnameChanging(value);
					this.SendPropertyChanging();
					this._us_lastname = value;
					this.SendPropertyChanged("us_lastname");
					this.Onus_lastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string us_address
		{
			get
			{
				return this._us_address;
			}
			set
			{
				if ((this._us_address != value))
				{
					this.Onus_addressChanging(value);
					this.SendPropertyChanging();
					this._us_address = value;
					this.SendPropertyChanged("us_address");
					this.Onus_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_birthday", DbType="Date NOT NULL")]
		public System.DateTime us_birthday
		{
			get
			{
				return this._us_birthday;
			}
			set
			{
				if ((this._us_birthday != value))
				{
					this.Onus_birthdayChanging(value);
					this.SendPropertyChanging();
					this._us_birthday = value;
					this.SendPropertyChanged("us_birthday");
					this.Onus_birthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_gender", DbType="Char(1) NOT NULL")]
		public char us_gender
		{
			get
			{
				return this._us_gender;
			}
			set
			{
				if ((this._us_gender != value))
				{
					this.Onus_genderChanging(value);
					this.SendPropertyChanging();
					this._us_gender = value;
					this.SendPropertyChanged("us_gender");
					this.Onus_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_phone", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string us_phone
		{
			get
			{
				return this._us_phone;
			}
			set
			{
				if ((this._us_phone != value))
				{
					this.Onus_phoneChanging(value);
					this.SendPropertyChanging();
					this._us_phone = value;
					this.SendPropertyChanged("us_phone");
					this.Onus_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string us_email
		{
			get
			{
				return this._us_email;
			}
			set
			{
				if ((this._us_email != value))
				{
					this.Onus_emailChanging(value);
					this.SendPropertyChanging();
					this._us_email = value;
					this.SendPropertyChanged("us_email");
					this.Onus_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_role", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string us_role
		{
			get
			{
				return this._us_role;
			}
			set
			{
				if ((this._us_role != value))
				{
					this.Onus_roleChanging(value);
					this.SendPropertyChanging();
					this._us_role = value;
					this.SendPropertyChanged("us_role");
					this.Onus_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Order", Storage="_Orders", ThisKey="us_username", OtherKey="us_username")]
		public EntitySet<Order> Orders
		{
			get
			{
				return this._Orders;
			}
			set
			{
				this._Orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Transaction", Storage="_Transactions", ThisKey="us_username", OtherKey="us_username")]
		public EntitySet<Transaction> Transactions
		{
			get
			{
				return this._Transactions;
			}
			set
			{
				this._Transactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Transactions(Transaction entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Transactions(Transaction entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_BaoCaoDoanhThu")]
	public partial class View_BaoCaoDoanhThu
	{
		
		private int _id;
		
		private string _us_username;
		
		private float _totalprice;
		
		private System.DateTime _createdate;
		
		public View_BaoCaoDoanhThu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string us_username
		{
			get
			{
				return this._us_username;
			}
			set
			{
				if ((this._us_username != value))
				{
					this._us_username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalprice", DbType="Real NOT NULL")]
		public float totalprice
		{
			get
			{
				return this._totalprice;
			}
			set
			{
				if ((this._totalprice != value))
				{
					this._totalprice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="Date NOT NULL")]
		public System.DateTime createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				if ((this._createdate != value))
				{
					this._createdate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_DanhSachHangDaDat")]
	public partial class View_DanhSachHangDaDat
	{
		
		private string _us_username;
		
		private int _transactionID;
		
		private int _orderID;
		
		private string _pro_name;
		
		private int _or_quantity;
		
		private System.Nullable<float> _or_price;
		
		public View_DanhSachHangDaDat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string us_username
		{
			get
			{
				return this._us_username;
			}
			set
			{
				if ((this._us_username != value))
				{
					this._us_username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transactionID", DbType="Int NOT NULL")]
		public int transactionID
		{
			get
			{
				return this._transactionID;
			}
			set
			{
				if ((this._transactionID != value))
				{
					this._transactionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderID", DbType="Int NOT NULL")]
		public int orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				if ((this._orderID != value))
				{
					this._orderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_name
		{
			get
			{
				return this._pro_name;
			}
			set
			{
				if ((this._pro_name != value))
				{
					this._pro_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_quantity", DbType="Int NOT NULL")]
		public int or_quantity
		{
			get
			{
				return this._or_quantity;
			}
			set
			{
				if ((this._or_quantity != value))
				{
					this._or_quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_or_price", DbType="Real")]
		public System.Nullable<float> or_price
		{
			get
			{
				return this._or_price;
			}
			set
			{
				if ((this._or_price != value))
				{
					this._or_price = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_ThongKeSanPhamTheoDanhMuc")]
	public partial class View_ThongKeSanPhamTheoDanhMuc
	{
		
		private string _cate_name;
		
		private string _sup_name;
		
		private string _pro_name;
		
		private int _pro_quantity;
		
		private float _pro_firstprice;
		
		private float _pro_price;
		
		private System.DateTime _pro_nsx;
		
		private System.DateTime _pro_hsd;
		
		private string _pro_description;
		
		public View_ThongKeSanPhamTheoDanhMuc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cate_name
		{
			get
			{
				return this._cate_name;
			}
			set
			{
				if ((this._cate_name != value))
				{
					this._cate_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sup_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sup_name
		{
			get
			{
				return this._sup_name;
			}
			set
			{
				if ((this._sup_name != value))
				{
					this._sup_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_name
		{
			get
			{
				return this._pro_name;
			}
			set
			{
				if ((this._pro_name != value))
				{
					this._pro_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_quantity", DbType="Int NOT NULL")]
		public int pro_quantity
		{
			get
			{
				return this._pro_quantity;
			}
			set
			{
				if ((this._pro_quantity != value))
				{
					this._pro_quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_firstprice", DbType="Real NOT NULL")]
		public float pro_firstprice
		{
			get
			{
				return this._pro_firstprice;
			}
			set
			{
				if ((this._pro_firstprice != value))
				{
					this._pro_firstprice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="Real NOT NULL")]
		public float pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this._pro_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nsx", DbType="Date NOT NULL")]
		public System.DateTime pro_nsx
		{
			get
			{
				return this._pro_nsx;
			}
			set
			{
				if ((this._pro_nsx != value))
				{
					this._pro_nsx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_hsd", DbType="Date NOT NULL")]
		public System.DateTime pro_hsd
		{
			get
			{
				return this._pro_hsd;
			}
			set
			{
				if ((this._pro_hsd != value))
				{
					this._pro_hsd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_description", DbType="NVarChar(100)")]
		public string pro_description
		{
			get
			{
				return this._pro_description;
			}
			set
			{
				if ((this._pro_description != value))
				{
					this._pro_description = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
